### ISSUE TITLE
random-crop

### ISSUE THREAD

**Issue by sc-56** [Coloquinte/torchSR#10]
hi 

sorry for bothering, and recently i have used your scripts which really great work.

may i ask one question that "i have found "RandomCrop" is appended to training dataset, and i wonder how it works?

thanks a lot for your attention and support.

br,
sc

**Comment by Coloquinte** [comment]
Hi,

RandomCrop is used to pick a (small) part of the image. This is much faster and almost as good as using a whole 1920x1080 image at once. You can have a look at the help message or the code to learn more.

https://github.com/Coloquinte/torchSR/blob/44ddac16dfbb291c6725f80723fcf46d8f36c426/torchsr/transforms/transforms.py#L167

Thanks,
Gabriel

**Comment by sc-56** [comment]
many thx for the explanation, sorry,  and may i ask why this is used at the transformation training dataloader? does it mean every image can only take part of itself, and other parts would be missing?

**Comment by Coloquinte** [comment]
Yes it means that we only load a small, cropped image during training. There are multiple passes on the dataset, so that the whole image will be used over time.
