### ISSUE TITLE
Unable to find the paper for ninasr

### ISSUE THREAD

**Issue by lchunleo** [Coloquinte/torchSR#12]
Hi
  I am unable to find the paper for ninasr. Is it possible to provide the paper or a link ? Thanks

**Comment by Coloquinte** [comment]
Hi,
I didn't publish a paper, but there is a short description linked from the Readme, plus a bibtex snippet in case you want to cite.
Thank you

**Comment by lchunleo** [comment]
thanks. i read from your readme description, understand some references and ideas from other papers you had cited . it would be helpful to understand from the diagram of the network architecture as well.

**Comment by Coloquinte** [comment]
I don't know if I'll make a diagram anytime soon. In the meantime I suggest exporting to onnx and using [Netron ](https://netron.app/) to look at the network.
