### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [Coloquinte/torchSR#2]
Hi there!

First of all, amazing work! I am developing a CV library called [glasses](https://github.com/FrancescoSaverioZuppichini/glasses) and I was thinking to also add SR models and I came across your repo. 

What if we merge the two? Would you like to talk about it?

Let me know!

Thank you :)

Cheers,

Francesco

**Comment by Coloquinte** [comment]
Hi Francesco!

I had a look at glasses. It's an awesome project!

I'm always open to talk about SR models :) Don't hesitate to send me an email, and feel free to reuse the SR code and pretrained models.

As for merging the two, I feel that the two projects have different goals. With torchSR, I can provide datasets and training tools, which would be out of the scope of a more general vision project.

Thanks!
Gabriel

**Comment by FrancescoSaverioZuppichini** [comment]
Hey Gabriel, 

Thank you for the kind feedback! Since you are okay, I will definitely reuse some code and (of course) give credit to you.

I am not 100% sure that the two projects have different goals, my goal is to try to put as much computer vision staff as I can in the library while making it easy to use and I would like to also add SR models, datasets etc. I would like to also add Datasets, custom Losses etc but I lack the time and sometimes the knowledge. 

If you like the idea let me know and we can maybe have a chat :) 

Keep up the good work :)

Cheers, 

Francesco

**Comment by Coloquinte** [comment]
For custom SR losses, I suggest using [PIQ](https://github.com/photosynthesis-team/piq/) - this is what I use for training.

Let's follow up over email :)

**Comment by FrancescoSaverioZuppichini** [comment]
That's cool, I didn't know about it! Thanks :)
