### ISSUE TITLE
About the ssim and psnr of the package piq

### ISSUE THREAD

**Issue by OwXiaoM** [Coloquinte/torchSR#5]
Hello, I really love your program because it helps me a lot of understanding the image super-resolution via pytorch. However, I want to tell you something which I have found during my usage of running your code. I have compared the value of a same image group (Sr images and Hr images) from your code and other official methods, and I found a little difference when it executes the calculation of SSIM and PSNR between the PIQ (yours) and the official method of matlab (from the code of RCAN). Then I found the way of calculation of SSIM and PSNR from RCAN and SwinIR has the same value which is not the same as the PIQ method. So would you like that I provide you the calculation method from SwinIR, and we could make an intergration in to your code? If you are interested in that, don't be hesitate of contacting me.

**Comment by Coloquinte** [comment]
Hi,
Thank you!

The Matlab method adds additional shaving, and only computes the PSNR on the Jpeg luminance. As it's not true PSNR, it's only run with additional options: --shave-border $scale --eval-luminance. Do you still have a discrepancy with those?

**Comment by OwEnXiaoMing** [comment]
Hello, after adding the evaluation on Y channel and shave border with 2 pixel, the value still has a little difference, particularly for the baby in Set5, the ssim of PIQ is always higher than the matlab method, and I've found these might be some difference of calcutation between these methodes.

**Comment by OwEnXiaoMing** [comment]
As piq.ssim() has some parameters in the call of this function, maybe we need to change some parameters rather than it's default values.

**Comment by OwXiaoM** [comment]
Thanks, after trying that the values are the same now.

**Comment by Coloquinte** [comment]
You're welcome :)
