### ISSUE TITLE
A question of how you make it not exceed the the cuda memory

### ISSUE THREAD

**Issue by OwXiaoM** [Coloquinte/torchSR#6]
I have also a very intersting question to ask you that when I test the model on div2k validation set, my own codes always tells me that my cuda memory is run out, but in your code the same model works perfectly on the div2k validation set so how do you make this work?

**Comment by OwXiaoM** [comment]
Well I found it's really a silly question, actually I can make it work through cpu.

**Comment by Coloquinte** [comment]
Actually there are methods for this. The evaluation scripts usually have the --chop-size 400 option. For a pure Python use, utils.ChoppedModel does the trick.
